moodleUsername: admin
moodlePassword: YourStrongMoodlePass123
moodleEmail: admin@example.com

mariadb:
  enabled: false

externalDatabase:
  host: ${rds_endpoint}
  port: 3306
  user: admin
  password: ${rds_password}
  database: moodledb

persistence:
  enabled: true
  storageClass: "gp3"
  size: 5Gi

service:
  type: LoadBalancer

ingress:
  enabled: false

replicaCount: 2
